### ISSUE TITLE
github issue

### ISSUE THREAD

**Issue by rowanibrahem** [Abdallah5alifa/chat_app#1]
غير اسم الريبو ل chat app من غير تاسك 1 علشان دا ريبو للابلكيشن كله مش التاسك دا 

هنعمل برانش لكل فيتشر بعد كدا و نعمله ميرج ع الdev في الاخر يعني كان مفروض يكون فيه برانش splash و اما يتراجع و يخلص بنعمل ميرج علي الdev و نمسح البرانش

**Comment by Abdallah5alifa** [comment]
تمام فهمت حضرتك
