### ISSUE TITLE
core refactor

### ISSUE THREAD

**Issue by rowanibrahem** [Abdallah5alifa/chat_app#2]
في حاجات هنا مش صح كتير 
اول حاجة مش صح انك تحط الصور دايركت جوه فولدر الassets بتعمل فولدر اسمه images جوه assets و تحط جواه الصور 
تاني حاجة في كلاس الصور بعد static فيه const لان الصورة قيمة ثابته مش هتحمل كل مرة و مش احسن حاجة نحط string علشان كدا كدا هو هيتعمله detect انك حاطط path صورة ف عارف انها كدا مش محتاجين نكتب نوعها 
الtheme بقي فيه فولدر الcolors اللي هنستخدمها ف الابلكيشن ؟ 
و فايل الstyles سميه من غير كلمة theme 
الnaming مهم جدا جدا يا عبد الله دي من اساسيات الكلين كود 
ياريت تصلحه و ترفعه 
![image](https://github.com/user-attachments/assets/86601822-97df-42bf-9572-95eb3d2d5ea5)

**Comment by Abdallah5alifa** [comment]
تمام حاضر ياباشمهندسة
