### ISSUE TITLE
features refactor 

### ISSUE THREAD

**Issue by rowanibrahem** [Abdallah5alifa/chat_app#3]
فين الخط الاساسي مش محطوط في الmain ليه ؟ هيعرف الfont family اللي هيطبقها منين 
تقسيمة الsplash فين اللي مشينا عليها ف mvvm مفروض تكون كدا 
![Screenshot 2024-10-08 031714](https://github.com/user-attachments/assets/ba6b02e7-b8ba-4da9-a857-0d92fdf722d1)

صلحها و ارفعها لو مش فاهم حاجة ياريت تعرفني 
و متنقلش الكود تاني من chatGPT يا عبد الله

**Comment by Abdallah5alifa** [comment]
تمام صلحتها
انا منقلتش من chat والله بس عملت search وعرفتها 
لو عايزه تعملها بطريقه عاديه عادى هنستخدم future ونعملها

**Comment by Abdallah5alifa** [comment]
باشمهندسه الخط انا مش عارف اجيبه من figma

**Comment by rowanibrahem** [comment]
> باشمهندسه الخط انا مش عارف اجيبه من figma
اسمه inter
